image: node:latest

stages:
  - build
  - test

build-front:
  stage: build
  only:
    - merge_requests
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    name: frontend-${CI_COMMIT_SHORT_SHA}
    paths:
      - dist/

test-front:
  stage: test
  only:
    - merge_requests
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  script:
    - npm ci --prefer-offline
    - npm run test
